### ISSUE TITLE
Kubernetes/Swarm/Multiple instances

### ISSUE THREAD

**Issue by brockelmore** [slotix/dataflowkit#14]
Great work with this. I am wondering if you have deployed multiple instances behind a load balancer? Have you found a good way to do this, i.e. Traefik, some other kubernetes or docker swarm integration?

**Comment by slotix** [comment]
Thank you. 
We didn't try to deploy our dfk services to kubernetes cluster yet. 
But I think there would be no problem to use ready images for deployment:  slotix/dfk-fetch and slotix/dfk-parse.
