### ISSUE TITLE
How to Use Proxy with DataFlowKit?

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [slotix/dataflowkit#16]
How to use proxy to prevent blocking IPs? 
Plz give some example/guide tutorial with docker or standalone

**Comment by slotix** [comment]
"Chrome fetcher"
--------
https://github.com/slotix/dataflowkit/blob/afc0d3fe495fa97406d0034a4f386e4f88985d2c/docker-compose.yml#L9 
Uncomment the string starting from --proxy-server and enter here real IP address of proxy server.
 
"Base fetcher"
--------
https://github.com/slotix/dataflowkit/blob/d423a7b11b2849df5f4443b4be6c232dc3cf4167/docker-compose.yml#L40
add - --PROXY=http://username:password@proxy-host:port
 parameter after this string. This parameter is responsible for specifying proxy server for base fetcher requests.

**Comment by slotix** [comment]
Run "fetch.d" standalone server with --PROXY parameter as specified above to pass requests through a proxy server.

**Comment by NiNJAD3vel0per** [comment]
@slotix 
Thanks for the answer ! 
how to randomize proxy ip list in the ip pool or check and failover depending on whether its alive or not

**Comment by slotix** [comment]
You can use something like "super" proxy or proxy manager service which will rotate proxies and validate them before forwarding requests. So the whole scheme looks like dfk fetcher -> proxy manager -> pool of proxies. 

Chrome browser cannot rotate proxies in run time itself. The only possible way is to set up --proxy-server parameter at start. So you can point chrome to this proxy manager and it will do that work for you.
