### ISSUE TITLE
UI included?

### ISSUE THREAD

**Issue by uded** [slotix/dataflowkit#3]
Will the UI available for _toscrape_ data be published as a general service? Without that UI the whole service is... well, useful only to some extent...

**Comment by slotix** [comment]
For the moment you can use front-end at http://scrape.dataflowkit.org only or send POST requests directly to services using the CLI.

**Comment by uded** [comment]
OK, the service you mentioned returned 500 for anything but one URL I believe - so not very useful. And the true power of the tool lies in that UI actually. Just saying... :-)

**Comment by slotix** [comment]
Please can you provide more details about URL  submitted for parsing ?

**Comment by uded** [comment]
Sure. I have tried several of them:
* amazon.com
* rowery.org (my own service)
* few others

All of them returned 
> Error!
> Response with status: 500 Internal Server Error for URL: http://scrape.dataflowkit.org/fetch/splash

The only one that works is http://books.toscrape.com/

**Comment by slotix** [comment]
Please try again. It should work now.

**Comment by uded** [comment]
OK, looks way better know - I guess it was just a bug then ;-)
