### ISSUE TITLE
Adding option for bypassing render.

### ISSUE THREAD

**Issue by lutfuahmet** [slotix/dataflowkit#4]
Most of websites return same result whether fetch via browser or direct download. Can you add option for bypass?

**Comment by slotix** [comment]
Actually there are two endpoints to fetch content: base fetcher and splash fetcher. 
Base fetcher retrieves content directly. It is used to fetch robots.txt 
Splash is used to download web pages by default. 
It is possible to implement such functionality but it will take some time.

**Comment by slotix** [comment]
Choosing of Fetcher type is implemented. 
The last commit allows choosing fetcher Base Fetcher instead of Splash. 
Just set variable FETCHER_TYPE equal to "base".

**Comment by lutfuahmet** [comment]
thank you.

**Comment by slotix** [comment]
You can now define fetcher directly in JSON Payload file.
"fetcherType": "base" parameter is added there.
Read more at https://godoc.org/github.com/slotix/dataflowkit/parse/parse.d
