### ISSUE TITLE
Content behind login

### ISSUE THREAD

**Issue by klokocka** [slotix/dataflowkit#5]
I would like to scrape a website behind a login form (e.g. http://quotes.toscrape.com/login). Is Dataflowkit able to send forms and keep session information during scrapping? If yes, then how?

**Comment by slotix** [comment]
We are still testing this feature. I hope it will be available soon.

**Comment by klokocka** [comment]
OK, will be nice to have at least some alpha version to play with. If you can give me access to the testing version, then I might help with that...

**Comment by slotix** [comment]
Cookies handling is implemented for base fetcher. You can test it with http://scrape.dataflowkit.org

**Comment by slotix** [comment]
[The video ](https://youtu.be/cCVjgUuoEUA )demonstrates data extraction from pages behind login.
